apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-api
  namespace: ai-platform
spec:
  ingressClassName: traefik
  rules:
  - host: api.89.167.103.77.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notes-api
            port:
              number: 80
